### ISSUE TITLE
FYI: Functions v4 does not support proxies.json, current solution probably breaks on December

### ISSUE THREAD

**Issue by valstu** [macaw-cad/nextjs-on-azure#19]
Was playing around with the examples and noticed that v4 of Azure Functions do not support `proxies.json` file anymore. Beginning on December 3, 2022, function apps running on versions 2.x and 3.x of the Azure Functions runtime can no longer be supported.

Just doing some research if static server and server functions could be combined into one (catch all) endpoint with some conditional logic.

**Comment by erwinsmit** [comment]
@valstu Yeah, I saw the same, it's a shame that proxies can't be used anymore because I found them useful for other cases too.

I believe API management can also solve some of these problems, but it's just another product so I'm not sure what will happen to the total cost.

Please let us know if you found a good workaround!

**Comment by valstu** [comment]
Hey @erwinsmit, just wanted to let you know that Azure rolled out "native" support for SSR on Static Web Apps few days ago: https://techcommunity.microsoft.com/t5/apps-on-azure-blog/extending-next-js-support-in-azure-static-web-apps/ba-p/3627975?WT.mc_id=twitter-0000-azureadvocates

Although it is still in preview but might be a good alternative solution.

**Comment by erwinsmit** [comment]
Hi @valstu,

Thanks! I will try it out soon. It looks promising because it also supports the API routes. That would save a lot of trouble... 

Closing this issue for now, as we've solved the proxy issue by using a Yarp proxy instead. That also seems to work pretty good!
